steps:
  - label: ":hammer: Example Script"
    command: "script.sh"
    artifact_paths: "artifacts/*"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"

  - label: "prep"
    command: "pwd; mkdir test"
    
  - wait

  - label: "a"
    command: "sleep 3; whoami; pwd; ls"

  - label: "b"
    command: "sleep 3; whoami; pwd; ls"
   
  - wait
   
  - label: "Some other step"
    command: "sleep 3; ls asd; pwd"
