steps:
  - label: ":hammer: Example Script"
    command: "script.sh"
    artifact_paths: "artifacts/*"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"

  - label: "make a file..."
    command: "touch test"
    
  - wait
   
  - label: "...and its gone"
    command: "ls"
    
  - wait

  - label: "multiple cmds"
    commands:
      - "touch test > test"
      - "ls"

  - label: "foo"
    command: "date"
    
  - label: "foo"
    command: "date"
    
  - label: "foo"
    command: "date"
    
  - label: "foo"
    command: "date"
    
  - label: "foo"
    command: "date"
    
  - label: "foo"
    command: "date"
    
  - label: "foo"
    command: "date"
    
  - label: "foo"
    command: "date"
    
  - label: "foo"
    command: "date"
    
  - label: "foo"
    command: "date"
